### ISSUE TITLE
Does the model support *.png images?

### ISSUE THREAD

**Issue by madcat1991** [idealo/image-quality-assessment#24]
I'm getting an exception while trying to asses a PNG imageL
```
(master)$ ./predict  --docker-image nima-cpu --base-model-name MobileNet --weights-file $(pwd)/models/MobileNet/weights_mobilenet_technical_0.11.hdf5 --image-source $(pwd)/src/tests/test_images/src.png
Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-03-27 14:57:13.408342: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-27 14:57:13.413560: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2598115000 Hz
2019-03-27 14:57:13.414336: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x3def930 executing computations on platform Host. Devices:
2019-03-27 14:57:13.414620: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/src/handlers/data_generator.py", line 80, in __getitem__
    X, y = self.__data_generator(batch_samples)
  File "/src/handlers/data_generator.py", line 94, in __data_generator
    img = utils.load_image(img_file, self.img_load_dims)
  File "/src/utils/utils.py", line 39, in load_image
    return np.asarray(keras.preprocessing.image.load_img(img_file, target_size=target_size))
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 387, in load_img
    img = pil_image.open(path)
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/src/src.jpg'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/src/src.jpg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/evaluater/predict.py", line 73, in <module>
    main(**args.__dict__)
  File "/src/evaluater/predict.py", line 51, in main
    predictions = predict(nima.nima_model, data_generator)
  File "/src/evaluater/predict.py", line 30, in predict
    return model.predict_generator(data_generator, workers=8, use_multiprocessing=True, verbose=1)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2522, in predict_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: [Errno 2] No such file or directory: '/src/src.jpg'
```

The image is the same directory as the test images. The model works perfectly with the test JPGs.
```
(master)$ ./predict  --docker-image nima-cpu --base-model-name MobileNet --weights-file $(pwd)/models/MobileNet/weights_mobilenet_technical_0.11.hdf5 --image-source $(pwd)/src/tests/test_images/42039.jpg
Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-03-27 14:56:57.667077: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-27 14:56:57.671900: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2598115000 Hz
2019-03-27 14:56:57.672253: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x3c08380 executing computations on platform Host. Devices:
2019-03-27 14:56:57.672511: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>

1/1 [==============================] - 1s 810ms/step
[
  {
    "image_id": "42039",
    "mean_score_prediction": 4.647609725594521
  }
]
```

Are there any suggestions?

**Comment by clennan** [comment]
Hi, unfortunately the `predict.sh` script currently only works with jpg image files. 

Would be a great enhancement to change the image loading logic - currently the data generators need an `img_format` argument, which gets appended to the image id form the samples file. Would be much better to give the whole image file name in the samples file, e.g. `test_image_1.jpg` instead of `test_image_1`, and drop the `img_format` argument.

This would allow to also use png or other image formats that are supported by Pillow.
