### ISSUE TITLE
build cpu dockerfile problem with TF version?

### ISSUE THREAD

**Issue by fortunto2** [idealo/image-quality-assessment#48]
Hi
i build Dockerfile.cpu

and when predict

```
./predict  --docker-image nima-cpu --base-model-name MobileNet --weights-file $(pwd)/models/MobileNet/weights_mobilenet_technical_0.11.hdf5 --image-source /mnt/videos/data/frames/videos/1116l.mp4/001.jpg
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/evaluater/predict.py", line 73, in <module>
    main(**args.__dict__)
  File "/src/evaluater/predict.py", line 43, in main
    nima.build()
  File "/src/handlers/model_builder.py", line 35, in build
    self.base_model = BaseCnn(input_shape=(224, 224, 3), weights=self.weights, include_top=False, pooling='avg')
  File "/usr/local/lib/python3.6/dist-packages/keras/applications/mobilenet.py", line 248, in MobileNet
    img_input = Input(shape=input_shape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 1457, in Input
    input_tensor=tensor)
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 1319, in __init__
    name = prefix + '_' + str(K.get_uid(prefix))
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 68, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

```

**Comment by repollo** [comment]
nimitdesai92 has a working fork, it just needed to add the libraries from tensorflow. I had no idea how to do this since Im new to docker and had no idea how to change the docker image... 

After seeing nimitdesai92 fix keras import fork i realised it was way simpler than i thought...

**Comment by clennan** [comment]
We upgraded to TF2.0 and fixed the TF version in the Dockerfiles. Please try again and re-open if error persists.
